# Generated by Django 4.1.2 on 2022-11-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_relations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relations',
        ),
    ]
