# Generated by Django 4.1.2 on 2022-10-27 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (0, 'Female')], null=True)),
                ('birthday', models.DateField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='crew/')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateField(auto_now_add=True, null=True)),
                ('modified_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateField(auto_now_add=True, null=True)),
                ('modified_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateField(auto_now_add=True, null=True)),
                ('modified_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateField(auto_now_add=True, null=True)),
                ('modified_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now_add=True, null=True)),
                ('modified_time', models.DateField(auto_now=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.crew')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.movie')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.role')),
            ],
            options={
                'unique_together': {('movie', 'crew', 'role')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(through='imdb.MovieCrew', to='imdb.crew'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='imdb.genre'),
        ),
    ]
