# Generated by Django 4.1.2 on 2022-10-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='crew/'),
        ),
    ]
