# Generated by Django 4.1.2 on 2022-11-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_description_alter_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='movies/avatars/'),
        ),
    ]
