# Generated by Django 4.1.2 on 2022-11-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_crew_description_alter_crew_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='imdb_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
