# Generated by Django 4.1.2 on 2022-11-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_crew_imdb_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='imdb_score',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
