# Generated by Django 4.1.2 on 2022-11-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_crew_imdb_score_movie_imdb_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieCrew', to='movies.crew'),
        ),
    ]
