# Generated by Django 4.1.2 on 2022-11-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movierating_movierating_unique_user_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieRating',
        ),
    ]
